version: "3"
services:
  syncplay-server:
    image: godbone/syncplay-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8999:8999"
    environment:
     - PASSWORD=<You should add your own password here>